### ISSUE TITLE
Missing Linux installer

### ISSUE THREAD

**Issue by artberri** [bryanmacfarlane/svcinstall#2]
Hi @bryanmacfarlane !

There is no Linux installer, and what I understand from (this issue)[https://github.com/Microsoft/vso-agent/issues/105] in the vso-agent-installer package is that you are planning to use docker to support Linux.

I have successfully run the vso agent on Linux as a service with `systemd` and without docker, if I create the Linux installer based on systemd and I make a PR to this package, will you merge it if is fine?

If you aim is to not add that kind of support and you will not merge it, I will not spend my time doing it :P

**Comment by bryanmacfarlane** [comment]
Yes, we certainly take PRs.  Thanks

**Comment by bryanmacfarlane** [comment]
The interesting question is whether it's an option to specify systemd, initd etc... or does it inspect the system (it's ubuntu 15+ or cent os 7+ etc...) and just do the right thing?

**Comment by bryanmacfarlane** [comment]
To answer the other question, we will need to support Docker and run as a service

**Comment by artberri** [comment]
What I did is to support systemd, it thows an error if doesn't exist. I did already the PR: #3 

I didn't bump the version in the package.json, I suppose you will do before tagging a new version.

Let me know if you see something wrong or if you think that I should change something.
